module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    LEAD_EDIT: "LEAD_EDIT",
    GENRE_EDIT: "GENRE_EDIT",
    PLAYLIST_EDIT: "PLAYLIST_EDIT",
    DEFAULT: "",
    GENRE_ADD_NEW: "GENRE_ADD_NEW",
    PLAYLIST_ADD_NEW: "PLAYLIST_ADD_NEW",
    PLAYLIST_DELETE: "PLAYLIST_DELETE",
    GENRE_DELETE: "GENRE_DELETE",
    MENTALHEALTH_ADD_NEW: "MENTALHEALTH_ADD_NEW",
    MENTALHEALTH_EDIT: "MENTALHEALTH_EDIT",
    MENTALHEALTH_DELETE: "MENTALHEALTH_DELETE",
    QUESTION_ADD_NEW: "QUESTION_ADD_NEW",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
  },
});
